### PR TITLE
Adding ntp

### PR DESCRIPTION
**Pull request by jakub-pomykala**
address issue https://github.com/OpenLiberty/guides-common/issues/836

### CODE REVIEW

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
hi @jakub-pomykala 
this guide does not use minikube, no need to add `-u runner ` in scripts/dailyBuild.sh and scripts/dailyBuild.sh files

scripts/testApp.sh should use `./mvnw -ntp` instead of `mvn -ntp`

**Comment by jakub-pomykala** [comment]
@gkwan-ibm I've done the change but it looks like it's failing due to ./mvnw

**Comment by gkwan-ibm** [comment]
@jakub-pomykala 
let try to replace `mvnw` file, `mvnw.cmd` file, and `.mvn` directory from Liberty starter at the finish and start directories

**Comment by jakub-pomykala** [comment]
Closing due to duplicate PR (#119)

**Pull request closed without merging**
