### PR TITLE
Update to use Spring Boot 3.1.3 and springBoot-3.0 feature

### PR DESCRIPTION
**Pull request by tjwatson**
This PR cannot be used until the `springBoot-3.0` feature is published as a GA feature.

### CODE REVIEW

**Comment by gkwan-ibm** [comment]
address issue #129

**Comment by tjwatson** [comment]
Now that Spring Boot 3 support is GA for Open Liberty, can we get this one merged?

**Comment by gkwan-ibm** [comment]
We will work it out, such as review,  test, and fix the test automation, etc, before merge it

**Comment by gkwan-ibm** [comment]
Would you update the `.github/workflows/test.yml` [file](https://github.com/tjwatson/guide-spring-boot/blob/465c9829ae3086e4bf7e686513d78c84c71babfe/.github/workflows/test.yml#L50-L53) as following?

```
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
```

**Pull request merged**
