### PR TITLE
Update SEO

### PR DESCRIPTION
**Pull request by NimG98**
Issue: https://github.com/OpenLiberty/guides-common/issues/382

### CODE REVIEW

**Comment by NimG98** [comment]
Added `:page-search-keywords:` to metadata.
Similar to `guide-sessions`,  which had pretty good rankings on google search:
```
:page-search-keywords: ['sessions', 'session persistence', 'sessionCache', 'Hazelcast', 'JCache']
```
Didn't add keywords like `Java`, etc. to not overload page keywords, and Google thinks we're spamming

**Comment by NimG98** [comment]
> Is there a reason OpenLiberty was dropped from the title?

I dropped it to shorten the title, but Open Liberty is still mentioned in the seo description. 


I think the main goal of the guide is making a springboot application. 
And we want to attract users based on that part, 
and not on making a springboot application on a _specific server_. 

So it might not necessarily be important to mention in the title which server the application is running on (Open Liberty server).

**Comment by yeekangc** [comment]
Tagging @barecode @lauracowen in case they have comments.

**Comment by yeekangc** [comment]
I don't think we need the "Java" application?

**Pull request merged**
